const fakeData = 
[
    {
        '_id': '01',
        'title': 'Washington Avenue',
        'image': '../apart-mental-resources/images/Rectangle 405.png',
        'location': 'Nasirabad H/S, Chattogram',
        'bathroom': '2 Bathroom',
        'price': '$194',
        'bedrooms': '3 Bedrooms',
        'FlatSize' : '3000 Sq Feet',
        'Floor' :  'A5 (5th Floor) (6 storied Building ) (South Facing Unit)',
        'RoomCategory' : '3 Large Bed Rooms with 3 Verandas, Spacious Drawing, Dining & Family Living Room, Highly Decorated Kitchen with Store Room and Servant room with attached Toilet',
        'Facilities' : '1 Modern Lift, All Modern Amenities & Semi Furnished',
        'AdditionalFacilities' : 'a. Electricity with full generator load, b. Central Gas Geyser, c. 2 Car Parking with 1 Driver’s Accommodation, d. Community Conference Hall, e. Roof Top Beautified Garden and Grassy Ground, f. Cloth Hanging facility with CC camera',
    },
    {
        '_id': '02',
        'title': 'Washington Avenue',
        'image': '../apart-mental-resources/images/Rectangle 405.png',
        'location': 'Nasirabad H/S, Chattogram',
        'bathroom': '2 Bathroom',
        'price': '$194',
        'bedrooms': '3 Bedrooms',
        'FlatSize' : '3000 Sq Feet',
        'Floor' :  'A5 (5th Floor) (6 storied Building ) (South Facing Unit)',
        'RoomCategory' : '3 Large Bed Rooms with 3 Verandas, Spacious Drawing, Dining & Family Living Room, Highly Decorated Kitchen with Store Room and Servant room with attached Toilet',
        'Facilities' : '1 Modern Lift, All Modern Amenities & Semi Furnished',
        'AdditionalFacilities' : 'a. Electricity with full generator load, b. Central Gas Geyser, c. 2 Car Parking with 1 Driver’s Accommodation, d. Community Conference Hall, e. Roof Top Beautified Garden and Grassy Ground, f. Cloth Hanging facility with CC camera',
    },
    {
        '_id': '03',
        'title': 'Washington Avenue',
        'image': '../apart-mental-resources/images/Rectangle 405.png',
        'location': 'Nasirabad H/S, Chattogram',
        'bathroom': '2 Bathroom',
        'price': '$194',
        'bedrooms': '3 Bedrooms',
        'FlatSize' : '3000 Sq Feet',
        'Floor' :  'A5 (5th Floor) (6 storied Building ) (South Facing Unit)',
        'RoomCategory' : '3 Large Bed Rooms with 3 Verandas, Spacious Drawing, Dining & Family Living Room, Highly Decorated Kitchen with Store Room and Servant room with attached Toilet',
        'Facilities' : '1 Modern Lift, All Modern Amenities & Semi Furnished',
        'AdditionalFacilities' : 'a. Electricity with full generator load, b. Central Gas Geyser, c. 2 Car Parking with 1 Driver’s Accommodation, d. Community Conference Hall, e. Roof Top Beautified Garden and Grassy Ground, f. Cloth Hanging facility with CC camera',
    },
]